# Generated by Django 4.1.3 on 2022-11-28 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('provider', models.CharField(choices=[('ARAMEX', 'ARAMEX'), ('SMSA', 'SMSA'), ('SHIPBOX', 'SHIPBOX')], max_length=50)),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('number_of_pieces', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product_country', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_mobile', models.CharField(max_length=50)),
                ('sender_email', models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()])),
                ('sender_full_address', models.CharField(max_length=300)),
                ('sender_country', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_mobile', models.CharField(max_length=50)),
                ('receiver_email', models.CharField(max_length=200, validators=[django.core.validators.EmailValidator()])),
                ('receiver_full_address', models.CharField(max_length=300)),
                ('receiver_country', models.CharField(max_length=50)),
                ('shipping_date', models.DateTimeField()),
                ('tracking_id', models.CharField(max_length=200, null=True, unique=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'REGISTERED'), ('PENDING', 'PENDING'), ('TRANSIT', 'TRANSIT'), ('DELIVERED', 'DELIVERED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='REGISTERED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
